// Runtime helpers called by generic-value JIT'd code (the .so generated by
// jit.cpp). Exported from the syn executable (ENABLE_EXPORTS) so the dlopened
// module resolves them. They operate on NaN-boxed values via the thread-local
// current VM. The C ABI uses raw uint64_t (matching the generated code's
// `typedef uint64_t Value`) to guarantee register-compatible calling convention.
//
// CRITICAL GC INVARIANT: these helpers never trigger garbage collection. GC
// runs only at bytecode-instruction boundaries in VM::run_frame, where all live
// values sit in registers. JIT'd native frames hold live values in C locals
// that are NOT GC roots, so collecting mid-JIT would free them. Allocation here
// just bumps m_alloc_count; collection happens after control returns to the loop.
#include "synapse/runtime/vm.h"
#include "synapse/runtime/value.h"
#include "synapse/runtime/chunk.h"
#include <unordered_map>
#include <string>

using namespace syn;

static inline uint64_t R(Value v) { return v.raw; }
static inline Value    V(uint64_t r) { Value v; v.raw = r; return v; }

// JIT-local list pool: ObjLists created by JIT code are kept here instead of
// in m_gc_list so GC doesn't interfere mid-JIT. syn_rt_list_recycle puts them
// back; syn_rt_list_new_jit takes from here first. Drained after JIT __main__ exits.
static thread_local ObjList* tls_jit_list_pool = nullptr;

extern "C" {

uint64_t syn_rt_add(uint64_t a, uint64_t b) { return R(val_add(V(a), V(b))); }
uint64_t syn_rt_sub(uint64_t a, uint64_t b) { return R(val_sub(V(a), V(b))); }
uint64_t syn_rt_mul(uint64_t a, uint64_t b) { return R(val_mul(V(a), V(b))); }
uint64_t syn_rt_div(uint64_t a, uint64_t b) { return R(val_div(V(a), V(b))); }
uint64_t syn_rt_idiv(uint64_t a, uint64_t b){ return R(val_idiv(V(a), V(b))); }
uint64_t syn_rt_mod(uint64_t a, uint64_t b) { return R(val_mod(V(a), V(b))); }
uint64_t syn_rt_pow(uint64_t a, uint64_t b) { return R(val_pow(V(a), V(b))); }
uint64_t syn_rt_eq(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_eq(V(a), V(b)))); }
uint64_t syn_rt_neq(uint64_t a, uint64_t b) { return R(Value::from_bool(!val_eq(V(a), V(b)))); }
uint64_t syn_rt_lt(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_lt(V(a), V(b)))); }
uint64_t syn_rt_lte(uint64_t a, uint64_t b) { return R(Value::from_bool(val_lte(V(a), V(b)))); }
uint64_t syn_rt_gt(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_lt(V(b), V(a)))); }
uint64_t syn_rt_gte(uint64_t a, uint64_t b) { return R(Value::from_bool(val_lte(V(b), V(a)))); }

int syn_rt_truthy(uint64_t v) { return V(v).truthy() ? 1 : 0; }

uint64_t syn_rt_tuple_new(const uint64_t* elems, int n) {
    ObjList* t = tls_vm->alloc_list();
    t->kind = ObjKind::Tuple;
    t->items.assign(reinterpret_cast<const Value*>(elems),
                    reinterpret_cast<const Value*>(elems) + n);
    return R(Value::from_ptr(t));
}

uint64_t syn_rt_list_new(const uint64_t* elems, int n) {
    ObjList* l = tls_vm->alloc_list();
    l->items.assign(reinterpret_cast<const Value*>(elems),
                    reinterpret_cast<const Value*>(elems) + n);
    return R(Value::from_ptr(l));
}

// obj[key] = val for list (int key) or map (any key)
void syn_rt_index_set(uint64_t obj_, uint64_t key_, uint64_t val_) {
    Value obj = V(obj_), key = V(key_), val = V(val_);
    if (val_is_map(obj)) { as_map(obj).set(key, val); return; }
    if (obj.is_ptr()) {
        Obj* o = obj.as_ptr();
        if (o->kind == ObjKind::List || o->kind == ObjKind::Tuple) {
            auto& v = static_cast<ObjList*>(o)->items;
            int64_t idx = key.as_int();
            if (idx < 0) idx += int64_t(v.size());
            if (idx >= 0 && idx < int64_t(v.size())) v[size_t(idx)] = val;
        }
    }
}

void syn_rt_append(uint64_t list_, uint64_t val_) {
    Value list = V(list_);
    if (val_is_list(list)) as_list(list).items.push_back(V(val_));
}

void syn_rt_list_reserve(uint64_t list_, uint32_t n) {
    Value list = V(list_);
    if (val_is_list(list)) as_list(list).items.reserve(n);
}

uint64_t syn_rt_len(uint64_t obj_) {
    Value obj = V(obj_);
    if (val_is_string(obj)) return R(Value::from_int(int64_t(as_str(obj).data.size())));
    if (obj.is_ptr()) {
        Obj* o = obj.as_ptr();
        if (o->kind == ObjKind::List || o->kind == ObjKind::Tuple)
            return R(Value::from_int(int64_t(static_cast<ObjList*>(o)->items.size())));
        if (o->kind == ObjKind::Map)
            return R(Value::from_int(int64_t(static_cast<ObjMap*>(o)->pairs.size())));
    }
    return R(Value::from_int(0));
}

uint64_t syn_rt_map_new() { return R(Value::from_ptr(tls_vm->alloc_map())); }

// Generic obj.method(args) dispatch — routes through the same
// VM::invoke_method() the bytecode interpreter's INVOKE opcode uses, so
// every list/string/map method (split, join, upper, find, starts_with, ...)
// has exactly one implementation instead of a JIT-side reimplementation of
// each. `mid` is a MethodId cast to int by the generated code (jit.cpp
// already validated the field name resolves to a known MethodId before
// emitting this call).
uint64_t syn_rt_invoke_method(uint64_t obj, int mid, int nargs, const uint64_t* args) {
    return R(tls_vm->invoke_method(V(obj), MethodId(mid), nargs, (Value*)args));
}

// `key in container` — mirrors the interpreter's HAS_KEY opcode exactly
// (map: key lookup; list/tuple: linear equality scan).
uint64_t syn_rt_has_key(uint64_t container_, uint64_t key_) {
    Value container = V(container_), key = V(key_);
    if (val_is_map(container))
        return R(Value::from_bool(!as_map(container).get(key).is_none()));
    if (container.is_ptr() && uint8_t(container.as_ptr()->kind) - 1u <= 1u) {
        for (auto& x : static_cast<ObjList*>(container.as_ptr())->items)
            if (val_eq(x, key)) return R(Value::from_bool(true));
        return R(Value::from_bool(false));
    }
    return R(Value::from_bool(false));  // non-collection: JIT tier can't raise; caller falls back
}

// obj[key]: list/tuple (int key) or map (any key)
uint64_t syn_rt_index(uint64_t obj_, uint64_t key_) {
    Value obj = V(obj_), key = V(key_);
    if (val_is_map(obj)) return R(as_map(obj).get(key));
    if (obj.is_ptr()) {
        Obj* o = obj.as_ptr();
        if (o->kind == ObjKind::List || o->kind == ObjKind::Tuple) {
            auto& v = static_cast<ObjList*>(o)->items;
            int64_t idx = key.as_int();
            if (idx < 0) idx += int64_t(v.size());
            if (idx < 0 || idx >= int64_t(v.size())) return R(Value::none_val());
            return R(v[size_t(idx)]);
        }
    }
    return R(Value::none_val());
}

// Print a single value (matching Synapse's print() semantics, without newline)
static void _print_val(Value v) {
    std::string s = val_to_string(v);
    fputs(s.c_str(), stdout);
}

uint64_t syn_rt_str_lit(const char* s, int n) {
    return R(Value::from_ptr(tls_vm->intern_string(s, size_t(n))));
}

// Create a JIT-compiled closure without going through the interpreter.
// Finds the N-th ObjFunction constant inside outer_fn_name's bytecode,
// wraps upval values as closed ObjUpvalues, and returns the new ObjClosure.
// Key is (literal_ptr, nth) — stable because string literals live in the .so.
struct PtrIntHash {
    size_t operator()(const std::pair<const char*, int>& k) const {
        return std::hash<uintptr_t>{}((uintptr_t)k.first) ^ ((size_t)k.second * 2654435761u);
    }
};
using InnerFnMap = std::unordered_map<std::pair<const char*, int>, ObjFunction*, PtrIntHash>;
static thread_local InnerFnMap* tls_inner_fn_cache = nullptr;

uint64_t syn_rt_make_closure(const char* outer_fn_name, int nth_fn, int n_upvals, const uint64_t* upval_vals) {
    ObjFunction* inner_fn = nullptr;
    auto key = std::make_pair(outer_fn_name, nth_fn);
    if (tls_inner_fn_cache) {
        auto it = tls_inner_fn_cache->find(key);
        if (it != tls_inner_fn_cache->end()) inner_fn = it->second;
    }
    if (!inner_fn) {
        // First call: walk outer function's constants to find the Nth inner ObjFunction
        Value outer_val = tls_vm->get_global(outer_fn_name);
        if (!outer_val.is_ptr() || outer_val.as_ptr()->kind != ObjKind::Closure) return R(Value::none_val());
        ObjFunction* outer_fn = static_cast<ObjClosure*>(outer_val.as_ptr())->fn;
        int count = 0;
        for (auto& cv : outer_fn->chunk->constants) {
            if (cv.is_ptr() && cv.as_ptr()->kind == ObjKind::Function) {
                if (count == nth_fn) { inner_fn = static_cast<ObjFunction*>(cv.as_ptr()); break; }
                ++count;
            }
        }
        if (!inner_fn) return R(Value::none_val());
        if (!tls_inner_fn_cache) tls_inner_fn_cache = new InnerFnMap();
        (*tls_inner_fn_cache)[key] = inner_fn;
    }
    ObjClosure* cl = tls_vm->alloc<ObjClosure>(inner_fn);
    for (int i = 0; i < n_upvals && i < (int)cl->upvalues.size(); ++i) {
        ObjUpvalue* uv = tls_vm->alloc<ObjUpvalue>(nullptr);
        uv->closed = V(upval_vals[i]);
        uv->is_closed = true;
        cl->upvalues[i] = uv;
    }
    return R(Value::from_ptr(cl));
}

// JIT-local list allocation: bypasses GC list so GC won't touch these mid-JIT.
// Takes from tls_jit_list_pool (pre-warmed on reuse) or allocates fresh.
uint64_t syn_rt_list_new_jit(uint32_t reserve_n) {
    ObjList* l;
    if (tls_jit_list_pool) {
        l = tls_jit_list_pool;
        tls_jit_list_pool = (ObjList*)l->gc_next;
        l->gc_next = nullptr;
        l->kind = ObjKind::List;
        l->items.clear();  // preserves allocated capacity
    } else {
        l = new ObjList();
        l->gc_next = nullptr;  // not in m_gc_list
    }
    if (reserve_n > l->items._cap)
        l->items.reserve(reserve_n);
    return R(Value::from_ptr(l));
}

// Return a JIT-local list to the pool. Items are cleared (capacity preserved).
void syn_rt_list_recycle(uint64_t list_) {
    Value list = V(list_);
    if (!list.is_ptr() || list.as_ptr()->kind != ObjKind::List) return;
    ObjList* l = static_cast<ObjList*>(list.as_ptr());
    l->items.clear();
    l->gc_next = (Obj*)tls_jit_list_pool;
    tls_jit_list_pool = l;
}

// Drain the JIT list pool after JIT __main__ exits.
void syn_rt_drain_jit_pool() {
    ObjList* p = tls_jit_list_pool;
    while (p) { ObjList* next = (ObjList*)p->gc_next; delete p; p = next; }
    tls_jit_list_pool = nullptr;
}

void syn_rt_print1(uint64_t v_) { _print_val(V(v_)); fputc('\n', stdout); }

void syn_rt_print_n(const uint64_t* args, int n) {
    for (int i = 0; i < n; ++i) { if (i) fputc(' ', stdout); _print_val(V(args[i])); }
    fputc('\n', stdout);
}

// Fast closure call: checks jit_cache, falls back to interpreter.
// For use by value-JIT'd __main__ code calling closure variables.
uint64_t syn_rt_call_jitcl(uint64_t callee_, int nargs, const uint64_t* args_) {
    Value callee = V(callee_);
    if (!callee.is_ptr()) return R(Value::none_val());
    Obj* obj = callee.as_ptr();
    if (obj->kind != ObjKind::Closure) return R(tls_vm->call_fn(callee, nargs, (Value*)args_));
    ObjClosure* cl = static_cast<ObjClosure*>(obj);
    JitEntry* je = static_cast<JitEntry*>(cl->jit_cache);
    if (je == nullptr) {
        auto it = tls_vm->m_jit.find(cl->fn->name);
        je = (it != tls_vm->m_jit.end()) ? &it->second : reinterpret_cast<JitEntry*>(uintptr_t(1));
        cl->jit_cache = je;
    }
    if (reinterpret_cast<uintptr_t>(je) > 1 && je->closure_fn)
        return R(je->closure_fn(nargs, (Value*)args_,
                                reinterpret_cast<void**>(cl->upvalues.data())));
    return R(tls_vm->call_fn(callee, nargs, (Value*)args_));
}

// Generic value call: call any Value through the interpreter.
// Used by value-JIT'd code to call named functions not in vfns.
uint64_t syn_rt_call_val(uint64_t callee_, int nargs, const uint64_t* args_) {
    return R(tls_vm->call_fn(V(callee_), nargs, (Value*)args_));
}

// Look up a global by name, for value-JIT'd code calling non-JIT functions.
uint64_t syn_rt_get_global(const char* name) {
    return R(tls_vm->get_global(name));
}

// In-place string append: x = x + rhs, no new ObjString allocation.
// For string + string: appends rhs into *dst in-place (amortized O(1)).
// For other types: falls back to val_add (may allocate — safe only outside tight loops).
void syn_rt_str_inplace_add(uint64_t* dst, uint64_t rhs_) {
    Value d = V(*dst), r = V(rhs_);
    if (val_is_string(d) && val_is_string(r)) {
        ObjString* sd = &as_str(d);
        if (sd->is_interned) {
            // Interned strings are immutable — materialize a mutable copy
            ObjString* ns = tls_vm->alloc_string(sd->data.data(), sd->data.size());
            ns->data.append(as_str(r).data);
            ns->hash = 0;
            *dst = R(Value::from_ptr(ns));
            return;
        }
        sd->data.append(as_str(r).data);
        sd->hash = 0;
        return;
    }
    Value res = val_add(d, r);
    *dst = R(res);
    if (res.is_ptr()) {
        Obj* o = res.as_ptr(); o->gc_next = tls_vm->m_gc_list; tls_vm->m_gc_list = o;
        ++tls_vm->m_alloc_count;
    }
}

} // extern "C"
