// Runtime helpers called by generic-value JIT'd code (the .so generated by
// jit.cpp). Exported from the syn executable (ENABLE_EXPORTS) so the dlopened
// module resolves them. They operate on NaN-boxed values via the thread-local
// current VM. The C ABI uses raw uint64_t (matching the generated code's
// `typedef uint64_t Value`) to guarantee register-compatible calling convention.
//
// CRITICAL GC INVARIANT: these helpers never trigger garbage collection. GC
// runs only at bytecode-instruction boundaries in VM::run_frame, where all live
// values sit in registers. JIT'd native frames hold live values in C locals
// that are NOT GC roots, so collecting mid-JIT would free them. Allocation here
// just bumps m_alloc_count; collection happens after control returns to the loop.
#include "synapse/runtime/vm.h"
#include "synapse/runtime/value.h"

using namespace syn;

static inline uint64_t R(Value v) { return v.raw; }
static inline Value    V(uint64_t r) { Value v; v.raw = r; return v; }

extern "C" {

uint64_t syn_rt_add(uint64_t a, uint64_t b) { return R(val_add(V(a), V(b))); }
uint64_t syn_rt_sub(uint64_t a, uint64_t b) { return R(val_sub(V(a), V(b))); }
uint64_t syn_rt_mul(uint64_t a, uint64_t b) { return R(val_mul(V(a), V(b))); }
uint64_t syn_rt_div(uint64_t a, uint64_t b) { return R(val_div(V(a), V(b))); }
uint64_t syn_rt_idiv(uint64_t a, uint64_t b){ return R(val_idiv(V(a), V(b))); }
uint64_t syn_rt_mod(uint64_t a, uint64_t b) { return R(val_mod(V(a), V(b))); }
uint64_t syn_rt_pow(uint64_t a, uint64_t b) { return R(val_pow(V(a), V(b))); }
uint64_t syn_rt_eq(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_eq(V(a), V(b)))); }
uint64_t syn_rt_neq(uint64_t a, uint64_t b) { return R(Value::from_bool(!val_eq(V(a), V(b)))); }
uint64_t syn_rt_lt(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_lt(V(a), V(b)))); }
uint64_t syn_rt_lte(uint64_t a, uint64_t b) { return R(Value::from_bool(val_lte(V(a), V(b)))); }
uint64_t syn_rt_gt(uint64_t a, uint64_t b)  { return R(Value::from_bool(val_lt(V(b), V(a)))); }
uint64_t syn_rt_gte(uint64_t a, uint64_t b) { return R(Value::from_bool(val_lte(V(b), V(a)))); }

int syn_rt_truthy(uint64_t v) { return V(v).truthy() ? 1 : 0; }

uint64_t syn_rt_tuple_new(const uint64_t* elems, int n) {
    ObjList* t = tls_vm->alloc_list();
    t->kind = ObjKind::Tuple;
    t->items.assign(reinterpret_cast<const Value*>(elems),
                    reinterpret_cast<const Value*>(elems) + n);
    return R(Value::from_ptr(t));
}

uint64_t syn_rt_list_new(const uint64_t* elems, int n) {
    ObjList* l = tls_vm->alloc_list();
    l->items.assign(reinterpret_cast<const Value*>(elems),
                    reinterpret_cast<const Value*>(elems) + n);
    return R(Value::from_ptr(l));
}

// obj[key]: list/tuple (int key) or map (any key)
uint64_t syn_rt_index(uint64_t obj_, uint64_t key_) {
    Value obj = V(obj_), key = V(key_);
    if (val_is_map(obj)) return R(as_map(obj).get(key));
    if (obj.is_ptr()) {
        Obj* o = obj.as_ptr();
        if (o->kind == ObjKind::List || o->kind == ObjKind::Tuple) {
            auto& v = static_cast<ObjList*>(o)->items;
            int64_t idx = key.as_int();
            if (idx < 0) idx += int64_t(v.size());
            if (idx < 0 || idx >= int64_t(v.size())) return R(Value::none_val());
            return R(v[size_t(idx)]);
        }
    }
    return R(Value::none_val());
}

} // extern "C"
